apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {}
    http {
      server {
        listen 80;
        location / {
          root /usr/share/nginx/html;
        }
      }
      server {
        listen 8080;
        location /stub_status {
          stub_status;
        }
      }
    }
