apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/matthijs-baas-sogeti/nginx-demo.git'  # Replace with your public repo URL
    targetRevision: HEAD
    path: .   # Use '.' if the manifest is at the root, or 'manifests' if in a folder
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated: {}
