apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/your-username/your-repo.git"  # Replace with your repo URL
    path: "."  # Path to YAML files in the repo
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: nginx-demo
  syncPolicy:
    automated: {}
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: argocd
    syncOptions:
      - CreateNamespace=true
